### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by SergeAstapov** [mainmatter/ember-cookies#725]
@marcoow would you mind to cut and publish new release? This should be major per Semver due to min Node.js version bump.

There were no significant changes, however `ember-getowner-polyfill` was dropped.

I wonder if you would also be open to dropping support for Ember <3.8 and removing `ember-native-class-polyfill` from `dependencies` (although this is minor)

**Comment by SergeAstapov** [comment]
Hi @marcoow! do you think you can cut release at this point of time? would you like to include #733?

**Comment by BobrImperator** [comment]
Released 🙏
